parameters:
  key_name: demo-key
  image: cirros
  flavor: m2.supertiny
  private_net_name: demo123
  private_net_cidr: 10.100.1.0/24
  private_net_gateway: 10.100.1.1
  private_net_pool_start: 10.100.1.100
  private_net_pool_end: 10.100.1.110


